name: deploy
on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: gt-cs2110/autograder-base

jobs:
  build-base:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./base
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: IMAGE_VERSION=${{ steps.meta.outputs.version }}

      - name: Test Docker image
        env:
          TEST_TAG: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}
        run: |
          chmod +x test.sh
          ./test.sh
      
      - name: Push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  build-rest:
    runs-on: ubuntu-latest
    needs: [build-base]
    strategy:
      matrix:
        image: [javafx, lc3, c]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}-${{ matrix.image }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.image }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: IMAGE_VERSION=${{ steps.meta.outputs.version }}

      - name: Test Docker image
        env:
          TEST_TAG: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}-${{ matrix.image }}
        run: |
          chmod +x test.sh
          ./test.sh
      
      - name: Push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true